// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUFmX-MCh4bt0V3jFz5-O6MNSd_9fC5Pk',
    appId: '1:111528070491:web:50717822e1eda89b42de7e',
    messagingSenderId: '111528070491',
    projectId: 'porisrom-2022',
    authDomain: 'porisrom-2022.firebaseapp.com',
    databaseURL: 'https://porisrom-2022-default-rtdb.firebaseio.com',
    storageBucket: 'porisrom-2022.appspot.com',
    measurementId: 'G-YX5XJ5YWKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACCnMR08q_00DDqTN3R2J1QkIdZLs605M',
    appId: '1:111528070491:android:80dbffff9a3cf9a342de7e',
    messagingSenderId: '111528070491',
    projectId: 'porisrom-2022',
    databaseURL: 'https://porisrom-2022-default-rtdb.firebaseio.com',
    storageBucket: 'porisrom-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnT9xsa3h7HnMO-XGUFQWrR8uVYKfd0xE',
    appId: '1:111528070491:ios:653918f10977ddce42de7e',
    messagingSenderId: '111528070491',
    projectId: 'porisrom-2022',
    databaseURL: 'https://porisrom-2022-default-rtdb.firebaseio.com',
    storageBucket: 'porisrom-2022.appspot.com',
    iosClientId: '111528070491-t49982pdk2nabi8g2cli5hqr8ae6s2lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mehonotAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnT9xsa3h7HnMO-XGUFQWrR8uVYKfd0xE',
    appId: '1:111528070491:ios:aeb299772546752d42de7e',
    messagingSenderId: '111528070491',
    projectId: 'porisrom-2022',
    databaseURL: 'https://porisrom-2022-default-rtdb.firebaseio.com',
    storageBucket: 'porisrom-2022.appspot.com',
    iosClientId: '111528070491-77dd3i8jctef7njn9pi2rinqo8kh25fh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mehonotAdmin.RunnerTests',
  );
}
